#!/bin/bash
# I Wish I Knew — staging deploy (generated by the Release/Deploy Operator, /verity:ship).
# Runs ON the staging host as the deploy user, after deploy/staging/README.md §1
# (root-setup) has been done once. Usage:
#   ~/i-wish-i-knew/deploy.sh v0.0.1            # resolves the tag to a digest and pins it
#   ~/i-wish-i-knew/deploy.sh v0.0.1@sha256:…   # deploys an already-pinned reference
# Steps: pull pinned image → additive migrate → restart unit → verify /readyz and /healthz.
set -euo pipefail
ENV=/etc/i-wish-i-knew/env
IMAGE=ghcr.io/seanerama/i-wish-i-knew
REF="${1:?usage: deploy.sh <tag|tag@sha256:digest>}"
[ -w "$ENV" ] || { echo "cannot write $ENV (run root-setup first)"; exit 1; }

# 1. Resolve and pin the digest (never hand-copied).
if [[ "$REF" != *@sha256:* ]]; then
  docker pull "$IMAGE:$REF" >/dev/null
  DIGEST=$(docker image inspect --format '{{index .RepoDigests 0}}' "$IMAGE:$REF" | sed 's/.*@//')
  REF="$REF@$DIGEST"
fi
docker pull "$IMAGE:$REF" >/dev/null
echo "image: $IMAGE:$REF"

# 2. Remember the previous reference for rollback, then pin the new one.
PREV=$(sed -n 's/^IWIK_IMAGE_TAG=//p' "$ENV")
echo "previous: ${PREV:-<none>}"
sed -i "s#^IWIK_IMAGE_TAG=.*#IWIK_IMAGE_TAG=$REF#" "$ENV"

# 3. Additive migrations with the NEW image (safe for the still-running old one).
set -a; . "$ENV"; set +a
docker run --rm --network host -e DATABASE_URL="$DATABASE_URL" "$IMAGE:$REF" node packages/service/dist/migrate.js

# 4. Swap and verify. The unit's ExecStartPost already gates on /readyz.
sudo /usr/bin/systemctl restart i-wish-i-knew
for i in $(seq 1 45); do
  if curl -fsS "http://$HOST:$PORT/readyz" 2>/dev/null | grep -q '"ok":true'; then
    echo "readyz ok"; curl -fsS "http://$HOST:$PORT/healthz"; echo
    echo "deployed $REF (rollback: deploy.sh $PREV)"; exit 0
  fi
  sleep 2
done
echo "readyz not ok after 90s; rolling back to ${PREV:-<none>}" >&2
[ -n "$PREV" ] && sed -i "s#^IWIK_IMAGE_TAG=.*#IWIK_IMAGE_TAG=$PREV#" "$ENV" && sudo /usr/bin/systemctl restart i-wish-i-knew
exit 1
